#!/usr/bin/env python3
"""
brain-stats — the SINGLE SOURCE OF TRUTH for Octorato's headline counts.

Independent multidisciplinary review (2026-05-25) found the same facts (skill /
agent / division counts) stated DIFFERENTLY in every layer — README even
contradicted itself, and three reviewers produced three different agent counts
because each counted differently. The fix: ONE deterministic computation from
the filesystem, consumed by every surface. Never hardcode a count again.

CANONICAL DEFINITIONS (explicit so they're unambiguous forever):
  • Skill     = a directory under  ~/.claude/skills/<name>/  containing SKILL.md
  • Division  = an immediate subdirectory of ~/.claude/agents/ that is NOT in
                EXCLUDED_AGENT_DIRS and that contains >= 1 persona file
  • Persona   = a *.md file under a division dir (recursive — personas may be
                nested in sub-categories), excluding README.md and index files

EXCLUDED_AGENT_DIRS are reference material, not specialist personas:
  • examples/  — workflow examples + README
  • strategy/  — executive briefs, playbooks, runbooks (has nested non-persona md)

Usage:
  python3 brain-stats.py            # human summary to stdout
  python3 brain-stats.py --json     # machine JSON (stats.json shape)
  python3 brain-stats.py --markers  # the <!-- BRAIN-STATS --> block for docs
  python3 brain-stats.py --write    # write ~/.claude/stats.json (canonical artifact)
"""
from __future__ import annotations
import argparse, json, pathlib, sys, datetime
import sys

# Force UTF-8 on stdout/stderr so the ✓ / ✗ / em-dash glyphs in reports
# survive on Windows shells defaulting to cp1252. Without this, a script
# can do its work correctly and still crash with UnicodeEncodeError when
# printing success. Applied repo-wide by _apply-utf8-reconfigure.py.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass


# Resolve the brain from THIS script's location, not ~/.claude: in a CI
# checkout (or a dimension worktree) home has no brain and the count was 0,
# failing the counts-render check on every PR since it was born (#113).
BRAIN = pathlib.Path(__file__).resolve().parent.parent
SKILLS_DIR = BRAIN / "skills"
AGENTS_DIR = BRAIN / "agents"
EXCLUDED_AGENT_DIRS = {"examples", "strategy"}
NON_PERSONA_FILES = {"README.md", "REGISTRY.md", "index.md", "_index.md"}


def count_skills() -> int:
    if not SKILLS_DIR.is_dir():
        return 0
    return sum(1 for d in SKILLS_DIR.iterdir() if d.is_dir() and (d / "SKILL.md").is_file())


def agent_divisions() -> dict[str, int]:
    """Return {division_name: persona_count} for real divisions only."""
    out: dict[str, int] = {}
    if not AGENTS_DIR.is_dir():
        return out
    for d in sorted(AGENTS_DIR.iterdir()):
        if not d.is_dir() or d.name in EXCLUDED_AGENT_DIRS:
            continue
        personas = [
            f for f in d.rglob("*.md")         # recursive: personas may be nested in
            if f.name not in NON_PERSONA_FILES  # sub-categories (e.g. game-development/godot/)
        ]
        if personas:
            out[d.name] = len(personas)
    return out


def compute() -> dict:
    divs = agent_divisions()
    return {
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "skills": count_skills(),
        "agents": sum(divs.values()),
        "divisions": len(divs),
        "by_division": divs,
        "definitions": {
            "skill": "dir under skills/ with SKILL.md",
            "division": "immediate subdir of agents/ (excl examples,strategy) with >=1 persona",
            "persona": "*.md under a division dir (recursive), excl README/REGISTRY/index",
        },
    }


def markers(stats: dict) -> str:
    return (
        "<!-- BRAIN-STATS:START (auto-generated by scripts/brain-stats.py — do not edit by hand) -->\n"
        f"**{stats['skills']} skills · {stats['agents']} agent personas across "
        f"{stats['divisions']} divisions**\n"
        "<!-- BRAIN-STATS:END -->"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--markers", action="store_true")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    stats = compute()

    if args.write:
        (BRAIN / "stats.json").write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {BRAIN / 'stats.json'}: {stats['skills']} skills, "
              f"{stats['agents']} agents, {stats['divisions']} divisions")
        return 0
    if args.json:
        print(json.dumps(stats, indent=2))
        return 0
    if args.markers:
        print(markers(stats))
        return 0

    print(f"Skills:    {stats['skills']}")
    print(f"Agents:    {stats['agents']}  (personas, excl {sorted(EXCLUDED_AGENT_DIRS)})")
    print(f"Divisions: {stats['divisions']}")
    print("By division:")
    for d, n in sorted(stats["by_division"].items(), key=lambda x: -x[1]):
        print(f"  {d:<22} {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
